# Generated by Django 2.2.7 on 2020-09-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0065_cambio_valor_setting_key_server'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grabacion',
        ),
    ]
