# Generated by Django 2.2.7 on 2021-12-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0082_grupo_limitar_agendas_personales'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='forzar_despausa',
            field=models.BooleanField(default=False, verbose_name='Forzar despausa'),
        ),
    ]
