# Generated by Django 2.2.7 on 2022-12-07 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_proveedor', models.IntegerField(choices=[(0, 'Twilio'), (1, 'Meta'), (2, 'GupShup')])),
                ('identificador', models.CharField(max_length=100)),
                ('token_autorizacion', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='configuracionproveedor_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='configuracionproveedor_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
