# Generated by Django 2.2.7 on 2022-12-14 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0018_regex_did_entrante_patron_de_discado_saliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whatsapp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionproveedor',
            name='token_autorizacion',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('identificador', models.CharField(max_length=100)),
                ('es_verificado', models.BooleanField(default=False)),
                ('token_validacion', models.CharField(max_length=100)),
                ('mensaje_bienvenida', models.TextField(blank=True, null=True)),
                ('mensaje_despedida', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='linea_created', to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='configuracion_telefonia_app.DestinoEntrante')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='whatsapp_app.ConfiguracionProveedor')),
                ('updated_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='linea_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
