# Generated by Django 2.2.7 on 2022-06-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_telefonia_app', '0018_regex_did_entrante_patron_de_discado_saliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicadeespera',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
